[package]
name = "utu_core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive", "alloc"] }
sha2 = "0.10.8"
wasm-bindgen = "0.2.93"

[lib]
crate-type = ["cdylib", "rlib"]
